---

dist: bionic

language: python
python: "3.7"
sudo: required

install:
  # Install ansible
  - pip install -U ansible

  # Check ansible version
  - ansible --version


script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
