---

dist: focal
language: minimal

env:
  - ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3

addons:
  apt:
    packages:
      - ansible
      - ansible-lint

install:
  # Check ansible versions
  - ansible --version
  - ansible-lint --version

script:
  - ansible-lint
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
