---

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - dbus
      - systemd-timesyncd
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Copy timesyncd default conf
  ansible.builtin.template:
    src: timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
    mode: 0644
  notify: restart_timesyncd
  become: yes

- name: Check status
  ansible.builtin.command: timedatectl -p NTP show
  become: yes
  register: timedatectl_show
  changed_when: no
  ignore_errors: true

- name: Enable timesync
  ansible.builtin.command: timedatectl set-ntp true
  become: yes
  when: timedatectl_show is failed or timedatectl_show.stdout | trim != "NTP=yes"
