---

- name: Purge legacy ntp clients
  ansible.builtin.apt:
    name: ntp
    state: absent
    purge: true
    force: true
  become: true

- name: Import enable.yml
  ansible.builtin.import_tasks: enable.yml
  when: "'virtualization_type' not in ansible_facts or ansible_facts.virtualization_type not in timesync_blacklist"

- name: Import disable.yml
  ansible.builtin.import_tasks: disable.yml
  when:
    - timesync_explicit_disable | default(false) | bool
    - "'virtualization_type' in ansible_facts"
    - ansible_facts.virtualization_type in timesync_blacklist
